name: AI Code Review

on:
  pull_request:
    types: [created, edited]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  REPO_URL: ${{ github.event.repository.html_url }}

jobs:
    generate_code_review:
      runs_on: windows-latest
      steps:
      - name: Checkout AI Code Review repository
        uses: actions/checkout@v2
        with:
          repository: Stradek/gpt-code-review-py
          path: ./gpt-code-review-py
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r ./gpt-code-review-py/requirements.txt
      - name: Execute AI Code Review script
        run: python ./gpt-code-review-py/src/gpt-code-review-py/main.py --pr_id $PR_NUMBER --repo_url $REPO_URL --output output.txt
      - name: Comment on PR with output from AI Code Review script
        shell: pwsh
        run: |
          $BODY = Get-Content -Path ./gpt-code-review-py/output.txt
          gh pr comment ${{ github.event.pull_request.number }} --body "$BODY"