name: Build Windows

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  configure:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Remove build directory files
      run: rmdir build -Recurse -Force 2> $null

    - name: Configure CMake
      run: cmake -G "Visual Studio 17 2022" -B build

    - name: Save build directory
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build
        
  build:
    needs: configure
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release, Debug]
        target: [Game, Editor]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Retrieve build directory
      uses: actions/download-artifact@v3
      with:
        name: build
        path: build

    - name: Build ${{matrix.target}} (${{matrix.configuration}})
      run: cmake --build build --config ${{matrix.configuration}} --target ${{matrix.target}}
