name: Build Windows

env:
  BUILD_DIR: "build/"

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  configure:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Remove build directory files
      run: |
        $buildDir = $BUILD_DIR
        if (Test-Path $buildDir)
        {
          Remove-Item $buildDir -Recurse -Force
        }

    - name: Configure CMake
      run: cmake -G "Visual Studio 17 2022" -B $BUILD_DIR

    - name: Save build directory
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: $BUILD_DIR
        
  build:
    needs: configure
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release, Debug]
        target: [Game, Editor]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Remove build directory files
      run: |
        $buildDir = $BUILD_DIR
        if (Test-Path $buildDir)
        {
          Remove-Item $buildDir -Recurse -Force
        }

    - name: Retrieve build directory
      uses: actions/download-artifact@v3
      with:
        name: build
        path: $BUILD_DIR

    - name: Build ${{matrix.target}} (${{matrix.configuration}})
      run: cmake --build $BUILD_DIR --config ${{matrix.configuration}} --target ${{matrix.target}}
