name: CMake

on: push

defaults:
  run:
    runs-on: windows-latest

jobs:
  configure:
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Configure CMake
      run: cmake -G "Visual Studio 17" -B build

    - name: Save build directory
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build
        
  build:
    needs: configure
    strategy:
      matrix:
        configuration: [Release, Debug]
        target: [Game, Editor, TracyProfilerTool]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Retrieve build directory
      uses: actions/download-artifact@v3
      with:
        name: build
        path: build

    - name: Build ${{matrix.target}} (${{matrix.configuration}})
      run: cmake --build build --config ${{matrix.configuration}} --target ${{matrix.target}}
