name: Sync back from main to develop

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync back to develop
        run: |
          git checkout develop
          git merge main --no-edit
          git push origin develop
