name: Sync develop with main

on:
  push:
    branches:
      - main

jobs:
  automerge:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Merge main into develop
      run: |
        git fetch origin
        git checkout develop
        git merge --no-edit main
        git push origin develop
