name: Sync develop with main

on:
  push:
    branches:
      - main

jobs:
  sync_branches:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch all branches
      run: git fetch --all

    - name: Checkout develop branch
      run: git checkout develop

    - name: Merge main into develop
      run: git merge --strategy=ours main

    - name: Push changes
      run: git push origin develop
